In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from nltk.corpus import stopwords 
from nltk.tokenize import WordPunctTokenizer

In [ ]:
import warnings
warnings.filterwarnings('ignore')

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
pwd

'/content'

In [ ]:
review = pd.read_csv('/content/drive/My Drive/ADM_Final/yelp_review.csv')
business = pd.read_csv('/content/drive/My Drive/ADM_Final/yelp_business_new.csv')

In [ ]:
review_new= pd.merge(review, business, on='business_id', how='inner')

In [ ]:
review.columns

Index(['review_id', 'user_id', 'business_id', 'stars', 'date', 'text',
       'useful', 'funny', 'cool'],
      dtype='object')

In [ ]:
review_new=review_new.drop(columns=['name','neighborhood','address','city','state','postal_code','latitude','longitude','stars_y','review_count','is_open','categories'])

In [ ]:
review_new

                      review_id                 user_id  ... funny  cool
0        vkVSCC7xljjrAI4UGfnKEQ  bv2nCi5Qv5vroFiqKGopiw  ...     0     0
1        vm1b1keOzwHjtGZEPPuYXA  xYciRtVZ1PW4IxSX4oJ1aw  ...     3     4
2        SXwA9KZ-Nc_hMARk_3cJ7g  5Ymfsf9fAYz-Ds_p0xawVQ  ...     0     3
3        jUzausdZ_ujqe_n8BlBj-g  DVOOF0Z627DyrZ4XKQbTgA  ...     0     0
4        oCRDwF3tszAkeszSfxwthg  5JoKz3mU42Cp906KRXDwJw  ...     0     1
...                         ...                     ...  ...   ...   ...
3175472  75rQjSash8QMsaBHmwFDaQ  6I1KT1SCGbAaTzTIMqF_eQ  ...     7     5
3175473  99hWXPtbpzXXbsL43RYuKA  sTcYq6goD1Fa2WS9MSkSvQ  ...     5     1
3175474  jMTIHP0bjofYRdJeQi4UJA  9IRuYmy5YmhtNQ6ei1p-uQ  ...     0     2
3175475  v0oh69A-IpFvowp138SaCg  NInHA5Rlv11P1W04pt36bA  ...     0     0
3175476  vLNJZC_eOQI7YF292fLHbA  jGbj8fl575EIQJcfaA1FKQ  ...     8     1

[3175477 rows x 9 columns]

In [ ]:
#Check Null values in Dataframe
review_new.isnull().sum()

review_id      0
user_id        0
business_id    0
stars_x        0
date           0
text           0
useful         0
funny          0
cool           0
dtype: int64

In [ ]:
review_new.head()

                review_id                 user_id  ... funny  cool
0  vkVSCC7xljjrAI4UGfnKEQ  bv2nCi5Qv5vroFiqKGopiw  ...     0     0
1  vm1b1keOzwHjtGZEPPuYXA  xYciRtVZ1PW4IxSX4oJ1aw  ...     3     4
2  SXwA9KZ-Nc_hMARk_3cJ7g  5Ymfsf9fAYz-Ds_p0xawVQ  ...     0     3
3  jUzausdZ_ujqe_n8BlBj-g  DVOOF0Z627DyrZ4XKQbTgA  ...     0     0
4  oCRDwF3tszAkeszSfxwthg  5JoKz3mU42Cp906KRXDwJw  ...     0     1

[5 rows x 9 columns]

In [ ]:
import string
import re
def clean_text(text):
    text = text.translate(string.punctuation)
    
    ## Convert words to lower case and split them
    text = text.lower().split()
    
    ## Remove stop words
    stops = set(stopwords.words("english"))
    text = [w for w in text if not w in stops and len(w) >= 3]
    
    text = " ".join(text)
    
    # Clean the text
    text = re.sub(r"[^A-Za-z0-9^,!.\/'+-=]", " ", text)
    text = re.sub(r"what's", "what is ", text)
    text = re.sub(r"\'s", " ", text)
    text = re.sub(r"\'ve", " have ", text)
    text = re.sub(r"n't", " not ", text)
    text = re.sub(r"i'm", "i am ", text)
    text = re.sub(r"\'re", " are ", text)
    text = re.sub(r"\'d", " would ", text)
    text = re.sub(r"\'ll", " will ", text)
    text = re.sub(r",", " ", text)
    text = re.sub(r"\.", " ", text)
    text = re.sub(r"!", " ! ", text)
    text = re.sub(r"\/", " ", text)
    text = re.sub(r"\^", " ^ ", text)
    text = re.sub(r"\+", " + ", text)
    text = re.sub(r"\-", " - ", text)
    text = re.sub(r"\=", " = ", text)
    text = re.sub(r"'", " ", text)
    text = re.sub(r"(\d+)(k)", r"\g<1>000", text)
    text = re.sub(r":", " : ", text)
    text = re.sub(r" e g ", " eg ", text)
    text = re.sub(r" b g ", " bg ", text)
    text = re.sub(r" u s ", " american ", text)
    text = re.sub(r"\0s", "0", text)
    text = re.sub(r" 9 11 ", "911", text)
    text = re.sub(r"e - mail", "email", text)
    text = re.sub(r"j k", "jk", text)
    text = re.sub(r"\s{2,}", " ", text)    
    return text

In [ ]:
yelp_data = review_new[['business_id', 'user_id', 'stars_x', 'text']]

In [ ]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [ ]:
yelp_data.iterrows

<bound method DataFrame.iterrows of                     business_id  ...                                               text
0        AEx2SYEUJmTxVVB18LlCwA  ...  Super simple place but amazing nonetheless. It...
1        AEx2SYEUJmTxVVB18LlCwA  ...  *The shop was featured on Mind of a Chef with ...
2        AEx2SYEUJmTxVVB18LlCwA  ...  As its name suggests, Wilensky's is a lunch co...
3        AEx2SYEUJmTxVVB18LlCwA  ...  Stopped by for the Wilensky's Special, loved i...
4        AEx2SYEUJmTxVVB18LlCwA  ...  I have to admit, I am a fan. Just entering the...
...                         ...  ...                                                ...
3175472  pHq_hlWqlB0QKexF7kO2mg  ...  Look, I don't have a problem with the concept....
3175473  pHq_hlWqlB0QKexF7kO2mg  ...  What genius came up with this idea? Let's see,...
3175474  tZYFHe0R0Gux_2Qt7kfOvA  ...  If you're looking for homecooking in the Kanna...
3175475  tZYFHe0R0Gux_2Qt7kfOvA  ...  Moved to the area in Nov. 2012, and pass by th...
3175476  tZYFHe0R0Gux_2Qt7kfOvA  ...  I thought that this would kill it but... What ...

[3175477 rows x 4 columns]>

In [ ]:
yelp_data=yelp_data[:100000]

In [ ]:
%%time
yelp_data['text'] = yelp_data['text'].apply(clean_text)

CPU times: user 29.2 s, sys: 2.06 s, total: 31.3 s
Wall time: 31.2 s

In [ ]:
review_new=review_new[:100000]

In [ ]:
#Split train test
vld_size=0.15
X_train, X_valid, y_train, y_valid = train_test_split(yelp_data['text'], review_new['business_id'], test_size = vld_size)

In [ ]:
userid_df = yelp_data[['user_id','text']]
business_df = yelp_data[['business_id', 'text']]

In [ ]:
userid_df = userid_df.groupby('user_id').agg({'text': ' '.join})
business_df = business_df.groupby('business_id').agg({'text': ' '.join})

In [ ]:
#userid vectorizer
userid_vectorizer = TfidfVectorizer(tokenizer = WordPunctTokenizer().tokenize, max_features=1000)
userid_vectors = userid_vectorizer.fit_transform(userid_df['text'])
userid_vectors.shape

(74505, 1000)

In [ ]:
#Business id vectorizer
businessid_vectorizer = TfidfVectorizer(tokenizer = WordPunctTokenizer().tokenize, max_features=1000)
businessid_vectors = businessid_vectorizer.fit_transform(business_df['text'])
businessid_vectors.shape

(289, 1000)

# Matrix Factorization

In [ ]:
userid_rating_matrix = pd.pivot_table(yelp_data, values='stars_x', index=['user_id'], columns=['business_id'])
userid_rating_matrix.shape

(74505, 289)

In [ ]:
userid_rating_matrix.head()

business_id             -P8dGzSVhJi-5oZ-8U2y0w  ...  zxJlg4XCHNoFy78WZPv89w
user_id                                         ...
---1lKK3aKOuomHnwAkAow                     NaN  ...                     NaN
---udAKDsn0yQXmzbWQNSw                     NaN  ...                     NaN
--2vR0DIsmQ6WfcSzKWigw                     NaN  ...                     NaN
--66hzx80CeVZcrm4AKJtQ                     NaN  ...                     NaN
--AujbGl6SYRaY8SFVNHXA                     NaN  ...                     NaN

[5 rows x 289 columns]

In [ ]:
P = pd.DataFrame(userid_vectors.toarray(), index=userid_df.index, columns=userid_vectorizer.get_feature_names())
Q = pd.DataFrame(businessid_vectors.toarray(), index=business_df.index, columns=businessid_vectorizer.get_feature_names())

In [ ]:
Q.head()

                               !         +  ...       yum     yummy
business_id                                 ...
-P8dGzSVhJi-5oZ-8U2y0w  0.159539  0.581547  ...  0.000000  0.000000
0-yj2jtzLUHG2b7PpEHyog  0.213796  0.672422  ...  0.014137  0.016176
0AQnRQw34IQW9-1gJkYnMA  0.364752  0.539380  ...  0.001264  0.007052
0H8PL4trSvZFYgPpvSOCjQ  0.110372  0.496673  ...  0.000000  0.000000
0NmTwqYEQiKErDv4a55obg  0.245636  0.700594  ...  0.005250  0.007122

[5 rows x 1000 columns]

In [ ]:
def matrix_factorization(R, P, Q, steps=1, gamma=0.001,lamda=0.02):
    for step in range(steps):
        for i in R.index:
            for j in R.columns:
                if R.loc[i,j]>0:
                    eij=R.loc[i,j]-np.dot(P.loc[i],Q.loc[j])
                    P.loc[i]=P.loc[i]+gamma*(eij*Q.loc[j]-lamda*P.loc[i])
                    Q.loc[j]=Q.loc[j]+gamma*(eij*P.loc[i]-lamda*Q.loc[j])
        e=0
        for i in R.index:
            for j in R.columns:
                if R.loc[i,j]>0:
                    e= e + pow(R.loc[i,j]-np.dot(P.loc[i],Q.loc[j]),2)+lamda*(pow(np.linalg.norm(P.loc[i]),2)+pow(np.linalg.norm(Q.loc[j]),2))
        if e<0.001:
            break
        
    return P,Q

In [ ]:
%%time
P, Q = matrix_factorization(userid_rating_matrix, P, Q, steps=1, gamma=0.001,lamda=0.02)

CPU times: user 16min 54s, sys: 41.5 s, total: 17min 35s
Wall time: 16min 46s

In [ ]:
#Store P, Q and vectorizer in pickle file
import pickle
output = open('recommendation.pkl', 'wb')
pickle.dump(P,output)
pickle.dump(Q,output)
pickle.dump(userid_vectorizer,output)
output.close()

## Prediction for input text

In [ ]:
words = 'I am intrested in vegeterian restaruents and I want eat falafal oh my god'
test_df= pd.DataFrame([words], columns=['text'])
test_df['text'] = test_df['text'].apply(clean_text)
test_vectors = userid_vectorizer.transform(test_df['text'])
test_v_df = pd.DataFrame(test_vectors.toarray(), index=test_df.index, columns=userid_vectorizer.get_feature_names())

predictItemRating=pd.DataFrame(np.dot(test_v_df.loc[0],Q.T),index=Q.index,columns=['Rating'])
topRecommendations=pd.DataFrame.sort_values(predictItemRating,['Rating'],ascending=[0])[:3]
topRecommendations

                          Rating
business_id
f4x1YBxkLrZg652xt2KR5g  0.303234
g8OnV26ywJlZpezdBnOWUQ  0.242146
XXW_OFaYQkkGOGniujZFHg  0.221566

## Prediction and Accuracy test on Validation set

In [ ]:
f = open('recommendation.pkl', 'rb')
P, Q, userid_vectorizer = pickle.load(f), pickle.load(f), pickle.load(f)

In [ ]:
test_df = pd.DataFrame([words], columns=['text'])
test_df['text'] = test_df['text'].apply(clean_text)
test_vectors = userid_vectorizer.transform(test_df['text'])
test_v_df = pd.DataFrame(test_vectors.toarray(), index=test_df.index,
                         columns=userid_vectorizer.get_feature_names())

In [ ]:
test_df = X_valid.to_frame()
test_df['text'] = test_df['text'].apply(clean_text)
test_vectors = userid_vectorizer.transform(test_df['text'])
test_v_df = pd.DataFrame(test_vectors.toarray(), index=test_df.index,
                         columns=userid_vectorizer.get_feature_names())

In [ ]:
y_pred = []
for key, row in test_v_df.iterrows():
    predictItemRating=pd.DataFrame(np.dot(row,Q.T),index=Q.index,columns=['Rating'])
    topRecommendations=pd.DataFrame.sort_values(predictItemRating,['Rating'],ascending=[0])[:1]
    y_pred.append(topRecommendations.index[0])

In [ ]:
#Calculate Accuracy
from sklearn.metrics import accuracy_score
print('Accuracy for validation set is: ',accuracy_score(y_valid, y_pred))